### PR TITLE
readme: fix gulp install issue

### PR DESCRIPTION
**Pull request by AliMD**
You must install gulp as global not gulp-cli

### CODE REVIEW

**Comment by AliMD** [comment]
travis-ci issue is not related to this pr

**Comment by ospatil** [comment]
The original text is correct. You will have to install `gulp-cli` globally and `gulp` locally. You can see this mentioned in the gulp documentation too - https://github.com/gulpjs/gulp/blob/master/docs/getting-started.md.

**Comment by AliMD** [comment]
The document is old, when you install `gulp-cli` and check version, gulp v1.2.1 installed
Check the gulp-cli release https://github.com/gulpjs/gulp-cli/releases or try yourself

**Comment by AliMD** [comment]
`gulp-cli` merge to gulp project and no separate project with separate version
the are same
check all other popular gulp plugin they all said  `npm i -g gulp` not `gulp-cli`

**Pull request closed without merging**
