### PR TITLE
remove legacy gulp support and use strict mode, closes #38

### LINKED ISSUE #38: Use typescript strict option
What do you think about upgrading to TypeScript 2.3 and using the [--strict](https://blog.mariusschulz.com/2017/06/09/typescript-2-3-the-strict-compiler-option) option? I ::heart:: strict code!

### PR DESCRIPTION
**Pull request by GaryB432**
The gulp template of `package.json` was [locked](https://nodesource.com/blog/semver-tilde-and-caret/) at TypeScript 2.0.0.  Hereby still locked but updated to 2.3.0 to support `--strict` . Not sure if you still need that that way.  Go ahead and unlock if you want.

### CODE REVIEW

**Comment by GaryB432** [comment]
hmm Sorry for the premature PR.  I see `master`'s generated gulp project is not getting along with prettier.

```
[10:14:45] Using gulpfile ~\stuff\gulpfile.js
[10:14:45] Starting 'lint'...
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: Invalid "extends" configuration value - could not require "tslint-config-prettier". 
Review the Node lookup algorithm (https://nodejs.org/api/modules.html#modules_all_together)
for the approximate method TSLint uses to find the referenced configuration file.
```

My global version of gulp may be too new because I just installed it this morning. Not too sure. I don't use gulp anymore.

**Comment by ospatil** [comment]
yeah, the gulp configuration is outdated. It's there only for historical reasons and 1.x setup. The generator started with gulp configuration and eventually I too moved away from it. I'll remove it in next major release.

**Comment by GaryB432** [comment]
That's what I figured.  Well I guess this PR is still good for the other configurations and it doesn't add too much extra breakage to the broken gulp one.

**Comment by GaryB432** [comment]
I'm almost ready to submit a PR with the new subgenerator I mentioned on another thread, i.e., to create the classes like `Greeter`.  It is working fine.  I can help clean out gulp after that if you like.

**Comment by ospatil** [comment]
Would appreciate the cleanup if it's not too much of a hassle to you.

**Comment by GaryB432** [comment]
did you mean some cleanup of this PR?  did you want me to remove all the gulp support?

**Comment by ospatil** [comment]
I was referring to the removal of gulp.

**Comment by GaryB432** [comment]
That seems like a different PR.  Should we just close this one?

**Comment by ospatil** [comment]
Sorry for being unclear in the earlier comment and thank you for the comprehensive PR 👍 .

**Pull request merged**
